### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by nikmd23** [Glimpse/Glimpse#226]
The following is a backlog of ideas that the team has had to improve Glimpse.
- [ ] **Performance/Memory Management Campaign**: Spend some time in CPU and memory profilers and trim off as much fat as possible from Glimpse. _(was #227)_
- [x] **Create Glimpse.WebForms NuPkg**: Remove the Glimpse.AspNet package and instead bundle that DLL in Glimpse.Mvc and create a Glimpse.WebForms package. _(was #232)_
- [ ] **Execution Tab UI**: Fix indenting on execution tab. _(was #233)_
- [ ] **Disable cookie buttons on Glimpse.axd if not needed**: Disable the buttons (and remove the new message @avanderhoorn added in #303) in Glimpse.axd if the `ControlCookiePolicy` isn't enabled. _(was #306)_
- [ ] **Cleanup ADO Project**: Make sure the code in this project follows the same conventions and naming rules as the rest of the code base (as defined in StyleCop). _(was #311)_
- [ ] **Create alternate ILMerge-free build**: Create an alternate `pack` command in our psake script that eschews ILMerge in favor of NuGet dependencies. The alternate NuGet package could be build and used locally. _(was #239)_
- [x] **Better documentation for Compression issues**: Detect if a user has turned on dynamic compression and put a message in the Glimpse.axd. _(was #339)_
- [ ] **XML documentation missing from NuGet package**: The Glimpse NuGet package has dlls in it but is missing XML documentation files, resulting in no intellisense documentation. _(was #352)_
- [ ] **Add link in Ado/EF timeline events tooltip to corresponding item in SQL tab**: Add a link in the event details in the timeline tab to the Command: executed tooltip to be able to jump to the corresponding item in the SQL tab. _(was #499)_
- [ ] **SharePoint 2010/13 Support**: Provide support for sharepoint. _(was #366)_
- [ ] **Scrollable Grids with Fixed Headers**: There can be a lot of data in the grids. It would be nice to have the ability to scroll through these grids with fixed headers so you don't forget what column you're looking at. _(was #432)_
- [ ] **Support for Grid Operations (i.e. Searching, Paging, Sorting, Filtering)**: Sometimes, it can be tedious to find a particular key or value that you're looking for in a grid of a tab. It would great to have support for client-side operations on grids like searching, paging, sorting, and filtering. _(was #433)_
- [ ] **Timeline's category area doesn't expand to fit categories**: Despite plenty of vertical space not all categories are visible. _(was #353)_
- [ ] **Visual Annotations for Transaction "Warnings" in SQL Tab**: When a transaction is started but left uncommitted, a warning icon is displayed and the font colour is set to orange. _(was #435)_
- [ ] **Non-Optimal Loading of Tabs with Large Amounts of Data**: The loading of tabs with large amounts of data appears to be non-optimal. _(was #449)_
- [ ] **List out top packages for first run in Glimpse.axd** _(was #340)_
- [ ] **Show stacktrace for all ado.net queries** _(was #472)_
- [ ] **Provide ability to create custom HUD panels** _(was #476)_
- [ ] **Make request with duplicate SQL queries more outstanding** _(was #552)_
- [ ] **Support for 304 status (not modified) for the ajax tab** _(was #562)_
- [ ] **Ajax requests to ASP.NET WebForms WebMethods are not captured** _(was #596)_
- [ ] **Glimpse.axd indicates newer version available even when latest version is installed, but only as long as the Glimpse client hasn't run after the upgrade** _(was #599)_
- [ ] **Symbole source package broken** _(was #630)_
- [ ] **Keyboard Shortcuts** _(was #651)_
- [ ] **Improve client script registration** _(was #656)_
- [ ] **Write an Azure Site Extension for Glimpse** _(was #694)_
- [ ] **Any plans to support AngularJS?** _(was #697)_
- [ ] **Automate version updates to assemblyinfo and nuspec files** _(was #707)_
- [ ] **Get Web API support up and running** _(was #715)_
- [ ] **Improve ViewState processing for Parameter Collections** _(was #725)_
- [ ] **Glimpse.WindowsAzure - what's next?** _(was #729)_
- [ ] **Owin/Katana support up and running** _(was #739)_
- [ ] **Support for System.Runtime.Caching classes** _(was #757)_
- [ ] **Add ability to sort requests by duration time** _(was #839)_
- [ ] **Add ability to filter requests over certain thresholds** _(was #840)_
- [ ] **Glimpse.ADO not working with Oracle Data Provider** _(was #871)_
- [ ] **X-Forwarded-Proto support** _(was #912)_
- [ ] **Date parameters are not quoted in SQL inspector** _(was #913)_
- [ ] **Glimpse SQL tab substitutes null parameters with 'NULL' instead of NULL** _(was #933)_
- [ ] **Glimpse does not permit open connection with azure tables** _(was #934)_
- [ ] **Customer ActionInvoker being overridden** _(was #328)_
- [ ] **Auto-format SQL in the SQL tab (command column)** _(was #958)_
- [ ] **Glimpse SQL tab is locked with AngularJs** _(was #953)_
- [ ] **Glimpse SQL tab substitutes null parameters with 'NULL' instead of NULL** _(was #933)_
- [ ] **Glimpse does not permit open connection with azure tables** _(was #934)_
- [ ] **Allow disable glimpse update check request?** _(was #941)_
- [ ] **Fix conflict with RazorEngine** _(was #942)_
- [ ] **Incorrect time zone offset displayed** _(was #908)_
